### ISSUE TITLE
Build fails iOS with Firebase

### ISSUE THREAD

**Issue by ncalderini** [rmtmckenzie/flutter_qr_mobile_vision#179]
Hello, thanks for this great package!

I'm having troubles trying to compile my app while using firebase, I'm getting a pod error

```
pod install --repo-update
Updating local specs repositories
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In snapshot (Podfile.lock):
    GoogleDataTransport (= 9.0.0, ~> 9.0)

  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 1.2.0, which depends on
      Firebase/CoreOnly (= 8.0.0) was resolved to 8.0.0, which depends on
        FirebaseCore (= 8.0.0) was resolved to 8.0.0, which depends on
          FirebaseCoreDiagnostics (~> 8.0) was resolved to 8.0.0, which depends on
            GoogleDataTransport (~> 9.0)

    qr_mobile_vision (from `.symlinks/plugins/qr_mobile_vision/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning was resolved to 0.60.0, which depends on
        GoogleMLKit/MLKitCore (= 0.60.0) was resolved to 0.60.0, which depends on
          MLKitCommon (~> 0.60.0) was resolved to 0.60.0, which depends on
            GoogleDataTransport (~> 3.2)


You have either:
 * changed the constraints of dependency `GoogleDataTransport` inside your development pod `qr_mobile_vision`.
   You should run `pod update GoogleDataTransport` to apply changes you've made.
```

My pubspec is:

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_messaging: ^10.0.0
  qr_mobile_vision: ^3.0.0
```

I also tried to use older firebase versions but error persists. Any help is appreciated!
