### ISSUE TITLE
Can you please support Barcode?

### ISSUE THREAD

**Issue by newbie-gk** [rmtmckenzie/flutter_qr_mobile_vision#4]
I checked out the package and tried it on some qrcodes, and it works great! Thank you so much :)
I tried it on barcodes and nothing showed up... Could this also be made to support barcodes?

**Comment by NatoBoram** [comment]
If this uses Google's [Mobile Vision](https://developers.google.com/vision/android/barcodes-overview) API, then it can be made to read both QR codes and barcodes.

**Comment by rmtmckenzie** [comment]
TBH I thought it would work by default, but I'll give it a look. I may have told it to only look for QR codes  as that's all I need, but it should be a quick fix. And I haven't tried it with image_picker so no idea if it causes a problem.

**Comment by NatoBoram** [comment]
If you can import `image_picker: "^0.3.1"` and `camera: "^0.1.2"` and see if it builds, I'm switching immediately!

**Comment by NatoBoram** [comment]
Hey! Concerning your [answer](https://stackoverflow.com/a/49537092/5083247), I'm having trouble to import it in a freshly created project.

```yaml
dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.4.0"
  uuid: "^0.5.3"
  #barcode_scan: "^0.0.3"
  #camera: "^0.1.2"
  image_picker: "^0.3.1"
  qr_mobile_vision:
    git:
      url: https://github.com/rmtmckenzie/flutter_qr_mobile_vision.git
      ref: static
```

```Bash
Git error. Command: git rev-list --max-count=1 static
fatal: ambiguous argument 'static': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
pub get failed (69) -- attempting retry 1 in 1 second...
```
