### ISSUE TITLE
Example failing on iPhone7

### ISSUE THREAD

**Issue by mondospaceman** [rmtmckenzie/flutter_qr_mobile_vision#53]
Create a new flutter project using example as main.dart.  Getting only black screen.

However, running example in your plug-in project works.  I'm assuming it's an invalid programmer at keyboard error, but is there additional set up I need to do?  Any clues?

Using pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  qr_mobile_vision: ^0.1.0
```
