### ISSUE TITLE
Turn flashlight on and off

### ISSUE THREAD

**Issue by rmtmckenzie** [rmtmckenzie/flutter_qr_mobile_vision#57]
Since the flashlight can't be manipulated externally it would be good to be able to turn it on with this plugin while the camera is active.

**Comment by rmtmckenzie** [comment]
Since more people have been seeing this, I'll try to address it soon. There has been a PR but I haven't had time to test it; if anyone who needs flash would be willing to give it a test on their devices and leave feedback here that would be much appreciated.

Add this to your pubspec to give it a try:
```yaml
dependency_overrides:
  qr_mobile_vision:
    git:
      url: https://github.com/adlanarifzr/flutter_qr_mobile_vision.git
      ref: '200fc00'
```
